//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion
    {
        public int Id { get; set; }
        public Nullable<bool> Ralladuras { get; set; }
        public Nullable<decimal> CantidadCombustible { get; set; }
        public Nullable<bool> GomaRepuesta { get; set; }
        public Nullable<bool> TieneGato { get; set; }
        public Nullable<bool> TieneRoturasCristal { get; set; }
        public string EstadoGomas { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_Vehiculo { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public Nullable<int> Id_User { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
