//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Inspeccions = new HashSet<Inspeccion>();
            this.Rentas = new HashSet<Renta>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string NoChasis { get; set; }
        public string NoMotor { get; set; }
        public string NoPlaca { get; set; }
        public Nullable<int> Id_TipoVehiculo { get; set; }
        public Nullable<int> Id_Marca { get; set; }
        public Nullable<int> Id_Modelo { get; set; }
        public Nullable<int> Id_Tipo_Combustible { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public Nullable<int> Id_User { get; set; }
    
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspeccion> Inspeccions { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renta> Rentas { get; set; }
        public virtual TipoCombustible TipoCombustible { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
